import { createExpense, updateSubscription } from "@repo/database";
import { addDays, addMonths, addYears } from "date-fns";
import { NextResponse } from "next/server";

export async function GET(request: Request) {
	// Verify cron secret
	const authHeader = request.headers.get("authorization");
	if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
		return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
	}

	try {
		// Find all active subscriptions with renewalDate <= today
		const today = new Date();
		today.setHours(0, 0, 0, 0);

		const { db } = await import("@repo/database");
		const subscriptions = await db.subscription.findMany({
			where: {
				status: "active",
				renewalDate: {
					lte: today,
				},
			},
			include: {
				expenseAccount: {
					include: {
						organization: {
							include: {
								expenseCategories: {
									where: {
										name: {
											contains: "subscription",
											mode: "insensitive",
										},
									},
									take: 1,
								},
							},
						},
					},
				},
			},
		});

		let expensesCreated = 0;
		const errors: string[] = [];

		for (const subscription of subscriptions) {
			try {
				// Find subscription category
				const { getExpenseCategoriesByOrganizationId } = await import(
					"@repo/database"
				);
				const categories = await getExpenseCategoriesByOrganizationId(
					subscription.expenseAccount.organizationId,
				);
				const category = categories.find(
					(cat) =>
						cat.name.toLowerCase().includes("subscription") ||
						cat.name.toLowerCase().includes("recurring"),
				);

				if (!category) {
					errors.push(
						`No subscription category found for expense account ${subscription.expenseAccount.id}`,
					);
					continue;
				}

				// Get first organization member as creator
				const { db } = await import("@repo/database");
				const firstMember = await db.member.findFirst({
					where: {
						organizationId:
							subscription.expenseAccount.organizationId,
					},
					select: {
						userId: true,
					},
				});

				if (!firstMember) {
					errors.push(
						`No members found for organization ${subscription.expenseAccount.organizationId}`,
					);
					continue;
				}

				// Create expense for this renewal
				await createExpense({
					businessId: subscription.expenseAccountId,
					categoryId: category.id,
					expenseType: "subscription",
					title: subscription.title,
					description: subscription.description || undefined,
					amount: Number(subscription.amount),
					currency: subscription.currency,
					conversionRate: subscription.conversionRate
						? Number(subscription.conversionRate)
						: undefined,
					rateType: subscription.rateType || undefined,
					baseCurrencyAmount: subscription.baseCurrencyAmount
						? Number(subscription.baseCurrencyAmount)
						: undefined,
					date: subscription.renewalDate,
					paymentMethodId: subscription.paymentMethodId || undefined,
					status: "active",
					createdBy: firstMember.userId,
					subscriptionId: subscription.id,
					isAutoGenerated: true,
				});

				// Calculate next renewal date based on frequency
				let nextRenewalDate: Date;
				if (subscription.renewalFrequency === "monthly") {
					nextRenewalDate = addMonths(subscription.renewalDate, 1);
				} else if (subscription.renewalFrequency === "yearly") {
					nextRenewalDate = addYears(subscription.renewalDate, 1);
				} else if (subscription.renewalFrequency === "weekly") {
					nextRenewalDate = addDays(subscription.renewalDate, 7);
				} else {
					nextRenewalDate = addMonths(subscription.renewalDate, 1); // Default to monthly
				}

				// Calculate next reminder date
				const nextReminderDate = addDays(
					nextRenewalDate,
					-subscription.reminderDays,
				);

				// Update subscription with new renewal date
				await updateSubscription({
					id: subscription.id,
					renewalDate: nextRenewalDate,
					nextReminderDate,
				});

				expensesCreated++;
			} catch (error) {
				const errorMessage =
					error instanceof Error
						? error.message
						: "Unknown error creating expense";
				errors.push(
					`Failed to process subscription ${subscription.id}: ${errorMessage}`,
				);
				console.error(
					`Error processing subscription ${subscription.id}:`,
					error,
				);
			}
		}

		return NextResponse.json({
			success: true,
			expensesCreated,
			errors: errors.length > 0 ? errors : undefined,
		});
	} catch (error) {
		console.error("Error processing subscription renewals:", error);
		return NextResponse.json(
			{ error: "Internal server error" },
			{ status: 500 },
		);
	}
}
