-- Step 1: Add new fields to Expense table
ALTER TABLE "expense" ADD COLUMN IF NOT EXISTS "subscriptionId" TEXT;
ALTER TABLE "expense" ADD COLUMN IF NOT EXISTS "isAutoGenerated" BOOLEAN DEFAULT false;

-- Step 2: Add new fields to Subscription table
ALTER TABLE "subscription" ADD COLUMN IF NOT EXISTS "expenseAccountId" TEXT;
ALTER TABLE "subscription" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "subscription" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "subscription" ADD COLUMN IF NOT EXISTS "currentAmount" DECIMAL;
ALTER TABLE "subscription" ADD COLUMN IF NOT EXISTS "currency" TEXT DEFAULT 'USD';
ALTER TABLE "subscription" ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP;
ALTER TABLE "subscription" ADD COLUMN IF NOT EXISTS "renewalType" TEXT DEFAULT 'from_renewal_date';
ALTER TABLE "subscription" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "subscription" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Step 3: Migrate existing data
-- Set expenseAccountId from expense.businessId
UPDATE "subscription" s
SET "expenseAccountId" = e."businessId"
FROM "expense" e
WHERE s."expenseId" = e.id;

-- Set title from expense.title
UPDATE "subscription" s
SET "title" = e.title
FROM "expense" e
WHERE s."expenseId" = e.id;

-- Set currentAmount from expense.amount
UPDATE "subscription" s
SET "currentAmount" = e.amount
FROM "expense" e
WHERE s."expenseId" = e.id;

-- Set currency from expense.currency
UPDATE "subscription" s
SET "currency" = COALESCE(e.currency, 'USD')
FROM "expense" e
WHERE s."expenseId" = e.id;

-- Set startDate from expense.date
UPDATE "subscription" s
SET "startDate" = e.date
FROM "expense" e
WHERE s."expenseId" = e.id;

-- Set subscriptionId on expense (link existing expenses to their subscriptions)
UPDATE "expense" e
SET "subscriptionId" = s.id
FROM "subscription" s
WHERE s."expenseId" = e.id AND e."subscriptionId" IS NULL;

-- Step 4: Make expenseId nullable (for backward compatibility during transition)
ALTER TABLE "subscription" ALTER COLUMN "expenseId" DROP NOT NULL;

-- Step 5: Add foreign key constraint for expenseAccountId
ALTER TABLE "subscription" 
ADD CONSTRAINT "subscription_expenseAccountId_fkey" 
FOREIGN KEY ("expenseAccountId") 
REFERENCES "expenseAccount"("id") 
ON DELETE CASCADE;

-- Step 6: Add foreign key constraint for subscriptionId on expense
ALTER TABLE "expense" 
ADD CONSTRAINT "expense_subscriptionId_fkey" 
FOREIGN KEY ("subscriptionId") 
REFERENCES "subscription"("id") 
ON DELETE SET NULL;

-- Step 7: Create indexes
CREATE INDEX IF NOT EXISTS "subscription_expenseAccountId_idx" ON "subscription"("expenseAccountId");
CREATE INDEX IF NOT EXISTS "expense_subscriptionId_idx" ON "expense"("subscriptionId");

-- Step 8: Update updatedAt trigger (if needed)
-- Note: Prisma will handle updatedAt automatically, but we can add a trigger if needed
